name: Deploy HTML with Apache and PHP

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Apache, PHP, and extensions
        run: |
          sudo apt update
          sudo apt install -y apache2 php php-mbstring php-xml php-mysql libapache2-mod-php

      - name: Copy website files
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp * /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 644 /var/www/html/

      - name: Restart Apache
        run: sudo systemctl restart apache2
